name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute tests
        working-directory: ./src
        run: |
          python -m pytest tests/ -v

      - run: echo "Execute Docker Build"
      - run: echo "Sends Docker Image to Docker Hub"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - run: echo "Get code"
      - run: echo "Execute Docker Build"
      - run: echo "Sends Docker Image to Docker Hub"
